import {
  Aperture,
  Asterisk,
  BellRing,
  Blend,
  Braces,
  Calculator,
  CalendarClock,
  CaseSensitive,
  Code2,
  Crop,
  Earth,
  FileCode2,
  FileImage,
  FileSearch,
  FileText,
  FileType,
  Fingerprint,
  GitCompareArrows,
  GitPullRequest,
  Globe,
  Hash,
  Hourglass,
  Images,
  KeyRound,
  Layers,
  Link2,
  ListOrdered,
  ListTree,
  LockKeyhole,
  type LucideIcon,
  Mail,
  Minimize2,
  Network,
  Paintbrush,
  Palette,
  Pencil,
  Pilcrow,
  QrCode,
  Quote,
  Regex,
  Route,
  Ruler,
  Search,
  Server,
  Share2,
  Sigma,
  Smartphone,
  Sparkles,
  SquareCode,
  SquareFunction,
  TableProperties,
  Terminal,
  TextQuote,
  Timer,
  TimerReset,
  Wand2,
} from 'lucide-react'
import type { Locale } from '@/i18n/dictionaries'

export type ToolCategory =
  | 'converters'
  | 'calculators'
  | 'time'
  | 'encoders'
  | 'formatters'
  | 'generators'
  | 'testers'
  | 'search'
  | 'text'
  | 'images'
  | 'network'
export type ToolDefinition = {
  slug: string
  pathSlug: string
  emoji: string
  category: ToolCategory
  icon: LucideIcon
  title: Record<Locale, string>
  description: Record<Locale, string>
  mode: 'convert' | 'generate' | 'inspect'
  workspace?:
    | 'default'
    | 'calculator'
    | 'scientific-calculator'
    | 'number-base'
    | 'unit-convert'
    | 'timezone'
    | 'timer'
    | 'stopwatch'
    | 'time-signal'
    | 'image-format'
    | 'image-compress'
    | 'drawing'
    | 'png-transparent'
    | 'heic-convert'
    | 'regex'
    | 'url-parser'
    | 'text-analyzer'
    | 'markdown'
    | 'mermaid'
    | 'cron'
    | 'subnet'
    | 'json-query'
    | 'qr-code'
    | 'base64-image'
    | 'curl'
    | 'jwt'
    | 'hmac'
    | 'basic-auth'
    | 'text-diff'
    | 'site-diagnostics'
    | 'color'
    | 'lorem'
    | 'string-escape'
    | 'list-utils'
    | 'selector'
    | 'glob'
    | 'svg'
    | 'image-convert'
    | 'exif'
    | 'x-search'
    | 'google-search'
    | 'gmail-search'
    | 'github-search'
    | 'whois'
    | 'ogp-check'
    | 'seo-check'
}

export const tools: ToolDefinition[] = [
  {
    slug: 'curl',
    emoji: '🌐',
    pathSlug: 'curl-code-converter',
    category: 'converters',
    icon: Terminal,
    title: { ja: 'cURL・コード変換', en: 'cURL to code' },
    description: { ja: 'cURLを各言語のHTTPコードへ変換', en: 'Convert cURL to HTTP client code' },
    mode: 'convert',
    workspace: 'curl',
  },
  {
    slug: 'json-csv',
    emoji: '📊',
    pathSlug: 'json-csv-converter',
    category: 'converters',
    icon: TableProperties,
    title: { ja: 'JSON ↔ CSV', en: 'JSON ↔ CSV' },
    description: { ja: 'JSON配列とCSVを相互変換', en: 'Convert between JSON arrays and CSV' },
    mode: 'convert',
  },
  {
    slug: 'yaml-json',
    emoji: '🔄',
    pathSlug: 'yaml-to-json',
    category: 'converters',
    icon: Braces,
    title: { ja: 'YAML ↔ JSON', en: 'YAML ↔ JSON' },
    description: { ja: 'YAMLとJSONを相互変換', en: 'Convert between YAML and JSON' },
    mode: 'convert',
  },
  {
    slug: 'json-toml',
    emoji: '🧾',
    pathSlug: 'json-toml-converter',
    category: 'converters',
    icon: FileCode2,
    title: { ja: 'JSON ↔ TOML', en: 'JSON ↔ TOML' },
    description: { ja: 'TOML設定とJSONを相互変換', en: 'Convert between TOML config and JSON' },
    mode: 'convert',
  },
  {
    slug: 'json-xml',
    emoji: '🧷',
    pathSlug: 'json-xml-converter',
    category: 'converters',
    icon: SquareCode,
    title: { ja: 'JSON ↔ XML', en: 'JSON ↔ XML' },
    description: { ja: 'XML文書とJSONを相互変換', en: 'Convert between XML documents and JSON' },
    mode: 'convert',
  },
  {
    slug: 'color',
    emoji: '🎨',
    pathSlug: 'color-converter',
    category: 'converters',
    icon: Palette,
    title: { ja: 'カラー変換・コントラスト', en: 'Color converter & contrast' },
    description: {
      ja: 'HEX/RGB/HSLを変換しWCAG比を確認',
      en: 'Convert HEX/RGB/HSL and check WCAG ratios',
    },
    mode: 'convert',
    workspace: 'color',
  },
  {
    slug: 'number-base',
    emoji: '🔢',
    pathSlug: 'number-base-converter',
    category: 'converters',
    icon: Sigma,
    title: { ja: '基数変換', en: 'Number base' },
    description: {
      ja: '2〜36進数を同時に表示して変換',
      en: 'Convert and compare bases from 2 to 36',
    },
    mode: 'convert',
    workspace: 'number-base',
  },
  {
    slug: 'unit-convert',
    emoji: '📏',
    pathSlug: 'unit-converter',
    category: 'converters',
    icon: Ruler,
    title: { ja: '単位変換', en: 'Unit converter' },
    description: {
      ja: '長さ・面積・重さ・データ容量などを一覧で変換',
      en: 'Convert length, area, weight, data size and more at once',
    },
    mode: 'convert',
    workspace: 'unit-convert',
  },
  {
    slug: 'date-time',
    emoji: '🕐',
    pathSlug: 'unix-time-converter',
    category: 'converters',
    icon: CalendarClock,
    title: { ja: '日時変換', en: 'Date & time' },
    description: { ja: '日時とUnix timeを変換', en: 'Convert dates and Unix time' },
    mode: 'convert',
  },
  {
    slug: 'timezone',
    emoji: '🌏',
    pathSlug: 'timezone-converter',
    category: 'converters',
    icon: Earth,
    title: { ja: 'タイムゾーン変換', en: 'Time zone converter' },
    description: {
      ja: '同じ時刻を世界の各都市で見比べる',
      en: 'Compare one moment across cities worldwide',
    },
    mode: 'convert',
    workspace: 'timezone',
  },
  {
    slug: 'calculator',
    emoji: '🧮',
    pathSlug: 'calculator',
    category: 'calculators',
    icon: Calculator,
    title: { ja: '電卓', en: 'Calculator' },
    description: {
      ja: '式のまま計算して履歴を残す電卓',
      en: 'Evaluate expressions and keep the history',
    },
    mode: 'inspect',
    workspace: 'calculator',
  },
  {
    slug: 'scientific-calculator',
    emoji: '📐',
    pathSlug: 'scientific-calculator',
    category: 'calculators',
    icon: SquareFunction,
    title: { ja: '関数電卓', en: 'Scientific calculator' },
    description: {
      ja: '三角関数や対数、度数法・弧度法に対応',
      en: 'Trigonometry, logarithms, degrees and radians',
    },
    mode: 'inspect',
    workspace: 'scientific-calculator',
  },
  {
    slug: 'timer',
    emoji: '⏳',
    pathSlug: 'timer',
    category: 'time',
    icon: Hourglass,
    title: { ja: 'タイマー', en: 'Timer' },
    description: {
      ja: '残り時間を数えて終了時に音で知らせる',
      en: 'Count down and chime when the time is up',
    },
    mode: 'inspect',
    workspace: 'timer',
  },
  {
    slug: 'stopwatch',
    emoji: '⏱️',
    pathSlug: 'stopwatch',
    category: 'time',
    icon: TimerReset,
    title: { ja: 'ストップウォッチ', en: 'Stopwatch' },
    description: {
      ja: '1/100秒まで計測しラップを記録',
      en: 'Measure to a hundredth of a second and record laps',
    },
    mode: 'inspect',
    workspace: 'stopwatch',
  },
  {
    slug: 'time-signal',
    emoji: '🔔',
    pathSlug: 'time-signal',
    category: 'time',
    icon: BellRing,
    title: { ja: '時報', en: 'Time signal' },
    description: {
      ja: '117風の音声や時報音で時刻を知らせる',
      en: 'Announce the time with a 117-style voice or chime',
    },
    mode: 'inspect',
    workspace: 'time-signal',
  },
  {
    slug: 'base64',
    emoji: '🧬',
    pathSlug: 'base64-encoder-decoder',
    category: 'encoders',
    icon: LockKeyhole,
    title: { ja: 'Base64', en: 'Base64' },
    description: { ja: 'UTF-8文字列を安全に変換', en: 'Encode and decode UTF-8 text' },
    mode: 'convert',
  },
  {
    slug: 'url',
    emoji: '🔗',
    pathSlug: 'url-encoder-decoder',
    category: 'encoders',
    icon: Link2,
    title: { ja: 'URL', en: 'URL' },
    description: { ja: 'URLコンポーネントを変換', en: 'Encode and decode URL components' },
    mode: 'convert',
  },
  {
    slug: 'html',
    emoji: '🏷️',
    pathSlug: 'html-escape',
    category: 'encoders',
    icon: TextQuote,
    title: { ja: 'HTMLエスケープ', en: 'HTML escape' },
    description: { ja: 'HTML特殊文字をエスケープ', en: 'Escape HTML special characters' },
    mode: 'convert',
  },
  {
    slug: 'jwt',
    emoji: '🎫',
    pathSlug: 'jwt-decoder',
    category: 'encoders',
    icon: KeyRound,
    title: { ja: 'JWT署名検証', en: 'JWT verifier' },
    description: {
      ja: 'JWTの署名と標準claimを検証',
      en: 'Verify JWT signatures and standard claims',
    },
    mode: 'inspect',
    workspace: 'jwt',
  },
  {
    slug: 'hmac',
    emoji: '✍️',
    pathSlug: 'hmac-generator',
    category: 'encoders',
    icon: Hash,
    title: { ja: 'HMAC生成', en: 'HMAC generator' },
    description: { ja: 'Secret付きメッセージ署名を生成', en: 'Sign messages with a shared secret' },
    mode: 'generate',
    workspace: 'hmac',
  },
  {
    slug: 'basic-auth',
    emoji: '🔐',
    pathSlug: 'basic-auth-generator',
    category: 'encoders',
    icon: LockKeyhole,
    title: { ja: 'Basic認証', en: 'Basic authentication' },
    description: {
      ja: 'Basic認証ヘッダーを生成・解析',
      en: 'Generate and inspect Basic auth headers',
    },
    mode: 'convert',
    workspace: 'basic-auth',
  },
  {
    slug: 'string-escape',
    emoji: '🔤',
    pathSlug: 'string-escape-unescape',
    category: 'encoders',
    icon: Quote,
    title: { ja: '文字列エスケープ', en: 'String escape' },
    description: {
      ja: 'JSON/JS/SQL/正規表現向けにエスケープ',
      en: 'Escape strings for JSON, JS, SQL and regex',
    },
    mode: 'convert',
    workspace: 'string-escape',
  },
  {
    slug: 'json-format',
    emoji: '📘',
    pathSlug: 'json-formatter',
    category: 'formatters',
    icon: Braces,
    title: { ja: 'JSON整形', en: 'JSON formatter' },
    description: { ja: 'JSONを読みやすく整形', en: 'Format and validate JSON' },
    mode: 'convert',
  },
  {
    slug: 'sql-format',
    emoji: '🗃️',
    pathSlug: 'sql-formatter',
    category: 'formatters',
    icon: Code2,
    title: { ja: 'SQL整形', en: 'SQL formatter' },
    description: { ja: 'SQLクエリを整形', en: 'Format SQL queries' },
    mode: 'convert',
  },
  {
    slug: 'xml-format',
    emoji: '🧹',
    pathSlug: 'xml-formatter',
    category: 'formatters',
    icon: Code2,
    title: { ja: 'XML整形', en: 'XML formatter' },
    description: { ja: 'XMLを読みやすく整形', en: 'Format XML documents' },
    mode: 'convert',
  },
  {
    slug: 'yaml-format',
    emoji: '🧵',
    pathSlug: 'yaml-formatter',
    category: 'formatters',
    icon: Layers,
    title: { ja: 'YAML整形', en: 'YAML formatter' },
    description: { ja: 'YAMLを正規化して整形', en: 'Normalise and re-indent YAML' },
    mode: 'convert',
  },
  {
    slug: 'css-format',
    emoji: '💅',
    pathSlug: 'css-formatter',
    category: 'formatters',
    icon: Paintbrush,
    title: { ja: 'CSS整形', en: 'CSS formatter' },
    description: { ja: 'CSSのブロックを読みやすく整形', en: 'Re-indent CSS blocks for reading' },
    mode: 'convert',
  },
  {
    slug: 'html-format',
    emoji: '📰',
    pathSlug: 'html-formatter',
    category: 'formatters',
    icon: FileType,
    title: { ja: 'HTML整形', en: 'HTML formatter' },
    description: { ja: 'HTMLをインデントして整形', en: 'Indent HTML markup' },
    mode: 'convert',
  },
  {
    slug: 'uuid',
    emoji: '🆔',
    pathSlug: 'uuid-generator',
    category: 'generators',
    icon: Fingerprint,
    title: { ja: 'UUID生成', en: 'UUID generator' },
    description: { ja: 'UUID v4をまとめて生成', en: 'Generate UUID v4 values' },
    mode: 'generate',
  },
  {
    slug: 'password',
    emoji: '🔑',
    pathSlug: 'password-generator',
    category: 'generators',
    icon: Sparkles,
    title: { ja: 'パスワード生成', en: 'Password generator' },
    description: { ja: '安全なパスワードを生成', en: 'Generate secure passwords' },
    mode: 'generate',
  },
  {
    slug: 'lorem',
    emoji: '📄',
    pathSlug: 'lorem-ipsum-generator',
    category: 'generators',
    icon: Pilcrow,
    title: { ja: 'ダミーテキスト生成', en: 'Lorem Ipsum generator' },
    description: {
      ja: 'Lorem Ipsumと日本語ダミー文を生成',
      en: 'Generate Lorem Ipsum and Japanese filler text',
    },
    mode: 'generate',
    workspace: 'lorem',
  },
  {
    slug: 'hash',
    emoji: '#️⃣',
    pathSlug: 'hash-generator',
    category: 'generators',
    icon: Hash,
    title: { ja: 'ハッシュ', en: 'Hash' },
    description: { ja: 'SHAハッシュを計算', en: 'Calculate SHA hashes' },
    mode: 'generate',
  },
  {
    slug: 'x-search',
    emoji: '🔎',
    pathSlug: 'x-advanced-search',
    category: 'search',
    icon: Search,
    title: { ja: 'X高度な検索', en: 'X advanced search' },
    description: {
      ja: '条件からXの検索クエリとURLを組み立て',
      en: 'Build X search queries and jump to the results',
    },
    mode: 'generate',
    workspace: 'x-search',
  },
  {
    slug: 'google-search',
    emoji: '🌎',
    pathSlug: 'google-advanced-search',
    category: 'search',
    icon: Globe,
    title: { ja: 'Google高度な検索', en: 'Google advanced search' },
    description: {
      ja: '検索演算子を組み立ててGoogleで検索',
      en: 'Compose search operators and jump to Google',
    },
    mode: 'generate',
    workspace: 'google-search',
  },
  {
    slug: 'gmail-search',
    emoji: '📮',
    pathSlug: 'gmail-search-builder',
    category: 'search',
    icon: Mail,
    title: { ja: 'Gmail検索ビルダー', en: 'Gmail search builder' },
    description: {
      ja: '差出人や添付条件からGmailの検索式を作成',
      en: 'Build Gmail search queries from senders and filters',
    },
    mode: 'generate',
    workspace: 'gmail-search',
  },
  {
    slug: 'github-search',
    emoji: '🐙',
    pathSlug: 'github-advanced-search',
    category: 'search',
    icon: GitPullRequest,
    title: { ja: 'GitHub高度な検索', en: 'GitHub advanced search' },
    description: {
      ja: 'リポジトリやIssueの検索条件を組み立て',
      en: 'Build repository, code and issue search queries',
    },
    mode: 'generate',
    workspace: 'github-search',
  },
  {
    slug: 'regex',
    emoji: '🧪',
    pathSlug: 'regular-expression-tester',
    category: 'testers',
    icon: Regex,
    title: { ja: '正規表現テスター', en: 'Regular expression tester' },
    description: {
      ja: '正規表現の一致箇所とグループを確認',
      en: 'Inspect matches and capture groups',
    },
    mode: 'inspect',
    workspace: 'regex',
  },
  {
    slug: 'json-query',
    emoji: '🔍',
    pathSlug: 'jsonpath-schema-validator',
    category: 'testers',
    icon: Route,
    title: { ja: 'JSONPath・Schema検証', en: 'JSONPath & Schema' },
    description: { ja: 'JSONの抽出とSchema検証', en: 'Query and validate JSON data' },
    mode: 'inspect',
    workspace: 'json-query',
  },
  {
    slug: 'selector-tester',
    emoji: '🎯',
    pathSlug: 'css-selector-xpath-tester',
    category: 'testers',
    icon: ListTree,
    title: { ja: 'セレクタ・XPathテスター', en: 'Selector & XPath tester' },
    description: {
      ja: 'HTMLにCSSセレクタとXPathを試す',
      en: 'Run CSS selectors and XPath against HTML',
    },
    mode: 'inspect',
    workspace: 'selector',
  },
  {
    slug: 'glob-tester',
    emoji: '✳️',
    pathSlug: 'glob-pattern-tester',
    category: 'testers',
    icon: Asterisk,
    title: { ja: 'globパターンテスター', en: 'Glob pattern tester' },
    description: {
      ja: 'パスがglobに一致するか確認',
      en: 'Check which paths a glob pattern matches',
    },
    mode: 'inspect',
    workspace: 'glob',
  },
  {
    slug: 'text-analyzer',
    emoji: '🔠',
    pathSlug: 'text-analyzer-case-converter',
    category: 'text',
    icon: CaseSensitive,
    title: { ja: 'テキスト解析・ケース変換', en: 'Text analyzer & case converter' },
    description: { ja: '文字数を解析してケースを変換', en: 'Analyze text and convert its case' },
    mode: 'inspect',
    workspace: 'text-analyzer',
  },
  {
    slug: 'text-diff',
    emoji: '🆚',
    pathSlug: 'text-diff',
    category: 'text',
    icon: GitCompareArrows,
    title: { ja: 'テキストDiff', en: 'Text diff' },
    description: { ja: '2つのテキストの差分を比較', en: 'Compare differences between two texts' },
    mode: 'inspect',
    workspace: 'text-diff',
  },
  {
    slug: 'list-utils',
    emoji: '📋',
    pathSlug: 'list-formatter',
    category: 'text',
    icon: ListOrdered,
    title: { ja: 'リスト整形', en: 'List formatter' },
    description: {
      ja: '並べ替え・重複除去・前後付与をまとめて',
      en: 'Sort, deduplicate and wrap lines in one pass',
    },
    mode: 'convert',
    workspace: 'list-utils',
  },
  {
    slug: 'markdown',
    emoji: '📝',
    pathSlug: 'markdown-preview',
    category: 'text',
    icon: FileText,
    title: { ja: 'Markdownプレビュー', en: 'Markdown preview' },
    description: { ja: 'Markdownを安全にプレビュー', en: 'Safely preview Markdown' },
    mode: 'inspect',
    workspace: 'markdown',
  },
  {
    slug: 'mermaid',
    emoji: '🧜',
    pathSlug: 'mermaid-editor',
    category: 'text',
    icon: GitPullRequest,
    title: { ja: 'Mermaidエディタ', en: 'Mermaid editor' },
    description: {
      ja: 'Mermaid記法のダイアグラムを編集・プレビュー',
      en: 'Edit and preview diagrams written in Mermaid',
    },
    mode: 'inspect',
    workspace: 'mermaid',
  },
  {
    slug: 'cron',
    emoji: '⏱️',
    pathSlug: 'cron-parser',
    category: 'converters',
    icon: Timer,
    title: { ja: 'Cron式ジェネレーター', en: 'Cron expression editor' },
    description: {
      ja: 'Cron式を組み立て、意味と次回実行日時を確認',
      en: 'Build cron expressions and check what they mean',
    },
    mode: 'inspect',
    workspace: 'cron',
  },
  {
    slug: 'qr-code',
    emoji: '📱',
    pathSlug: 'qr-code-generator',
    category: 'generators',
    icon: QrCode,
    title: { ja: 'QRコード生成', en: 'QR code generator' },
    description: { ja: 'テキストからQRコードを生成', en: 'Generate a QR code from text' },
    mode: 'generate',
    workspace: 'qr-code',
  },
  {
    slug: 'base64-image',
    emoji: '🖼️',
    pathSlug: 'base64-image-converter',
    category: 'images',
    icon: FileImage,
    title: { ja: 'Base64画像変換', en: 'Base64 image converter' },
    description: { ja: '画像とData URLを相互変換', en: 'Convert images and Data URLs' },
    mode: 'convert',
    workspace: 'base64-image',
  },
  {
    slug: 'svg-tools',
    emoji: '🖌️',
    pathSlug: 'svg-optimizer',
    category: 'images',
    icon: Blend,
    title: { ja: 'SVG最適化・プレビュー', en: 'SVG optimizer & preview' },
    description: {
      ja: '不要な情報を削りData URIも生成',
      en: 'Strip cruft and emit a CSS-ready data URI',
    },
    mode: 'convert',
    workspace: 'svg',
  },
  {
    slug: 'image-convert',
    emoji: '🗜️',
    pathSlug: 'image-converter',
    category: 'images',
    icon: Crop,
    title: { ja: '画像リサイズ・圧縮', en: 'Image resize & compress' },
    description: {
      ja: 'WebP/AVIF等へ変換しサイズを削減',
      en: 'Convert to WebP/AVIF and shrink the file',
    },
    mode: 'convert',
    workspace: 'image-convert',
  },
  {
    slug: 'image-format',
    emoji: '🖼',
    pathSlug: 'image-format-converter',
    category: 'images',
    icon: Images,
    title: { ja: '画像フォーマット変換', en: 'Image format converter' },
    description: {
      ja: 'PNG/JPEG/WebP/AVIFへまとめて変換',
      en: 'Batch convert to PNG, JPEG, WebP or AVIF',
    },
    mode: 'convert',
    workspace: 'image-format',
  },
  {
    slug: 'image-compress',
    emoji: '📉',
    pathSlug: 'image-compressor',
    category: 'images',
    icon: Minimize2,
    title: { ja: '画像圧縮', en: 'Image compressor' },
    description: {
      ja: '形式はそのままに複数画像をまとめて軽量化',
      en: 'Shrink several images at once, keeping their format',
    },
    mode: 'convert',
    workspace: 'image-compress',
  },
  {
    slug: 'drawing',
    emoji: '🖍️',
    pathSlug: 'drawing-tool',
    category: 'images',
    icon: Pencil,
    title: { ja: 'お絵描きツール', en: 'Drawing tool' },
    description: {
      ja: 'ブラウザで描いてPNGとして保存',
      en: 'Sketch in the browser and save it as a PNG',
    },
    mode: 'generate',
    workspace: 'drawing',
  },
  {
    slug: 'png-transparent',
    emoji: '🫧',
    pathSlug: 'png-transparency-maker',
    category: 'images',
    icon: Wand2,
    title: { ja: 'PNG透過', en: 'PNG transparency' },
    description: {
      ja: '指定した色を透明にしてPNGで書き出す',
      en: 'Knock out a colour and export a transparent PNG',
    },
    mode: 'convert',
    workspace: 'png-transparent',
  },
  {
    slug: 'heic-convert',
    emoji: '📱',
    pathSlug: 'heic-converter',
    category: 'images',
    icon: Smartphone,
    title: { ja: 'HEIC変換', en: 'HEIC converter' },
    description: {
      ja: 'iPhoneのHEIC写真をJPEG/PNGへ変換',
      en: 'Turn iPhone HEIC photos into JPEG or PNG',
    },
    mode: 'convert',
    workspace: 'heic-convert',
  },
  {
    slug: 'exif',
    emoji: '📸',
    pathSlug: 'exif-viewer',
    category: 'images',
    icon: Aperture,
    title: { ja: 'EXIF確認・削除', en: 'EXIF viewer & remover' },
    description: {
      ja: '撮影情報と位置情報を確認して削除',
      en: 'Inspect capture and location data, then strip it',
    },
    mode: 'inspect',
    workspace: 'exif',
  },
  {
    slug: 'subnet',
    emoji: '🕸️',
    pathSlug: 'ipv4-subnet-calculator',
    category: 'network',
    icon: Network,
    title: { ja: 'IPv4サブネット計算', en: 'IPv4 subnet calculator' },
    description: { ja: 'IPv4/CIDRのネットワーク範囲を計算', en: 'Calculate IPv4 network ranges' },
    mode: 'inspect',
    workspace: 'subnet',
  },
  {
    slug: 'url-parser',
    emoji: '🧭',
    pathSlug: 'url-parser',
    category: 'network',
    icon: Link2,
    title: { ja: 'URL解析', en: 'URL parser' },
    description: {
      ja: 'URLの構成要素とクエリを解析',
      en: 'Inspect URL components and query parameters',
    },
    mode: 'inspect',
    workspace: 'url-parser',
  },
  {
    slug: 'site-diagnostics',
    emoji: '🩺',
    pathSlug: 'dns-tls-http-ogp-diagnostics',
    category: 'network',
    icon: Network,
    title: { ja: 'DNS・TLS・HTTP・OGP診断', en: 'DNS, TLS, HTTP & OGP diagnostics' },
    description: {
      ja: 'ドメインとWebページをまとめて診断',
      en: 'Inspect a domain and web page in one request',
    },
    mode: 'inspect',
    workspace: 'site-diagnostics',
  },
  {
    slug: 'whois',
    emoji: '🗂️',
    pathSlug: 'whois-lookup',
    category: 'network',
    icon: Server,
    title: { ja: 'WHOIS検索', en: 'WHOIS lookup' },
    description: {
      ja: 'ドメインの登録者・期限・ステータスを照会',
      en: 'Look up a domain registrar, dates and status',
    },
    mode: 'inspect',
    workspace: 'whois',
  },
  {
    slug: 'ogp-check',
    emoji: '🪪',
    pathSlug: 'ogp-checker',
    category: 'network',
    icon: Share2,
    title: { ja: 'OGPチェック', en: 'OGP checker' },
    description: {
      ja: 'OGPとX Cardの設定をプレビューで確認',
      en: 'Preview Open Graph and X Card tags for a page',
    },
    mode: 'inspect',
    workspace: 'ogp-check',
  },
  {
    slug: 'seo-check',
    emoji: '🔬',
    pathSlug: 'seo-checker',
    category: 'network',
    icon: FileSearch,
    title: { ja: 'SEOチェック', en: 'SEO checker' },
    description: {
      ja: 'タイトルや見出し、canonicalなどを点検',
      en: 'Audit titles, headings, canonical tags and more',
    },
    mode: 'inspect',
    workspace: 'seo-check',
  },
  {
    slug: 'network-info',
    emoji: '📡',
    pathSlug: 'connection-info',
    category: 'network',
    icon: Network,
    title: { ja: 'ネットワーク情報', en: 'Network info' },
    description: { ja: 'ブラウザの接続情報を確認', en: 'Inspect browser network details' },
    mode: 'inspect',
  },
]

/** Display order for every surface that lists categories. */
export const categoryOrder: ToolCategory[] = [
  'converters',
  'calculators',
  'time',
  'encoders',
  'formatters',
  'generators',
  'testers',
  'search',
  'text',
  'images',
  'network',
]

export const findTool = (slug: string) => tools.find((tool) => tool.slug === slug)
export const findToolByPath = (category: string, pathSlug: string) =>
  tools.find((tool) => tool.category === category && tool.pathSlug === pathSlug)
export const toolsByCategory = (category: ToolCategory) =>
  tools.filter((tool) => tool.category === category)
