import {
  Aperture,
  Asterisk,
  Blend,
  Braces,
  CalendarClock,
  CaseSensitive,
  Code2,
  Crop,
  FileCode2,
  FileImage,
  FileText,
  FileType,
  Fingerprint,
  GitCompareArrows,
  Hash,
  KeyRound,
  Layers,
  Link2,
  ListOrdered,
  ListTree,
  LockKeyhole,
  type LucideIcon,
  Network,
  Paintbrush,
  Palette,
  Pilcrow,
  QrCode,
  Quote,
  Regex,
  Route,
  Sigma,
  Sparkles,
  SquareCode,
  TableProperties,
  Terminal,
  TextQuote,
  Timer,
} from 'lucide-react'
import type { Locale } from '@/features/i18n/domain/dictionaries'

export type ToolCategory =
  | 'converters'
  | 'encoders'
  | 'formatters'
  | 'generators'
  | 'testers'
  | 'text'
  | 'images'
  | 'network'
export type ToolDefinition = {
  slug: string
  pathSlug: string
  emoji: string
  category: ToolCategory
  icon: LucideIcon
  title: Record<Locale, string>
  description: Record<Locale, string>
  mode: 'convert' | 'generate' | 'inspect'
  workspace?:
    | 'default'
    | 'regex'
    | 'url-parser'
    | 'text-analyzer'
    | 'markdown'
    | 'cron'
    | 'subnet'
    | 'json-query'
    | 'qr-code'
    | 'base64-image'
    | 'curl'
    | 'jwt'
    | 'hmac'
    | 'basic-auth'
    | 'text-diff'
    | 'site-diagnostics'
    | 'color'
    | 'lorem'
    | 'string-escape'
    | 'list-utils'
    | 'selector'
    | 'glob'
    | 'svg'
    | 'image-convert'
    | 'exif'
}

export const tools: ToolDefinition[] = [
  {
    slug: 'curl',
    emoji: '🌐',
    pathSlug: 'curl-code-converter',
    category: 'converters',
    icon: Terminal,
    title: { ja: 'cURL・コード変換', en: 'cURL to code' },
    description: { ja: 'cURLを各言語のHTTPコードへ変換', en: 'Convert cURL to HTTP client code' },
    mode: 'convert',
    workspace: 'curl',
  },
  {
    slug: 'json-csv',
    emoji: '📊',
    pathSlug: 'json-csv-converter',
    category: 'converters',
    icon: TableProperties,
    title: { ja: 'JSON ↔ CSV', en: 'JSON ↔ CSV' },
    description: { ja: 'JSON配列とCSVを相互変換', en: 'Convert between JSON arrays and CSV' },
    mode: 'convert',
  },
  {
    slug: 'yaml-json',
    emoji: '🔄',
    pathSlug: 'yaml-to-json',
    category: 'converters',
    icon: Braces,
    title: { ja: 'YAML ↔ JSON', en: 'YAML ↔ JSON' },
    description: { ja: 'YAMLとJSONを相互変換', en: 'Convert between YAML and JSON' },
    mode: 'convert',
  },
  {
    slug: 'json-toml',
    emoji: '🧾',
    pathSlug: 'json-toml-converter',
    category: 'converters',
    icon: FileCode2,
    title: { ja: 'JSON ↔ TOML', en: 'JSON ↔ TOML' },
    description: { ja: 'TOML設定とJSONを相互変換', en: 'Convert between TOML config and JSON' },
    mode: 'convert',
  },
  {
    slug: 'json-xml',
    emoji: '🧷',
    pathSlug: 'json-xml-converter',
    category: 'converters',
    icon: SquareCode,
    title: { ja: 'JSON ↔ XML', en: 'JSON ↔ XML' },
    description: { ja: 'XML文書とJSONを相互変換', en: 'Convert between XML documents and JSON' },
    mode: 'convert',
  },
  {
    slug: 'color',
    emoji: '🎨',
    pathSlug: 'color-converter',
    category: 'converters',
    icon: Palette,
    title: { ja: 'カラー変換・コントラスト', en: 'Color converter & contrast' },
    description: {
      ja: 'HEX/RGB/HSLを変換しWCAG比を確認',
      en: 'Convert HEX/RGB/HSL and check WCAG ratios',
    },
    mode: 'convert',
    workspace: 'color',
  },
  {
    slug: 'number-base',
    emoji: '🔢',
    pathSlug: 'number-base-converter',
    category: 'converters',
    icon: Sigma,
    title: { ja: '基数変換', en: 'Number base' },
    description: { ja: '2〜36進数を自在に変換', en: 'Convert bases from 2 to 36' },
    mode: 'convert',
  },
  {
    slug: 'date-time',
    emoji: '🕐',
    pathSlug: 'unix-time-converter',
    category: 'converters',
    icon: CalendarClock,
    title: { ja: '日時変換', en: 'Date & time' },
    description: { ja: '日時とUnix timeを変換', en: 'Convert dates and Unix time' },
    mode: 'convert',
  },
  {
    slug: 'base64',
    emoji: '🧬',
    pathSlug: 'base64-encoder-decoder',
    category: 'encoders',
    icon: LockKeyhole,
    title: { ja: 'Base64', en: 'Base64' },
    description: { ja: 'UTF-8文字列を安全に変換', en: 'Encode and decode UTF-8 text' },
    mode: 'convert',
  },
  {
    slug: 'url',
    emoji: '🔗',
    pathSlug: 'url-encoder-decoder',
    category: 'encoders',
    icon: Link2,
    title: { ja: 'URL', en: 'URL' },
    description: { ja: 'URLコンポーネントを変換', en: 'Encode and decode URL components' },
    mode: 'convert',
  },
  {
    slug: 'html',
    emoji: '🏷️',
    pathSlug: 'html-escape',
    category: 'encoders',
    icon: TextQuote,
    title: { ja: 'HTMLエスケープ', en: 'HTML escape' },
    description: { ja: 'HTML特殊文字をエスケープ', en: 'Escape HTML special characters' },
    mode: 'convert',
  },
  {
    slug: 'jwt',
    emoji: '🎫',
    pathSlug: 'jwt-decoder',
    category: 'encoders',
    icon: KeyRound,
    title: { ja: 'JWT署名検証', en: 'JWT verifier' },
    description: {
      ja: 'JWTの署名と標準claimを検証',
      en: 'Verify JWT signatures and standard claims',
    },
    mode: 'inspect',
    workspace: 'jwt',
  },
  {
    slug: 'hmac',
    emoji: '✍️',
    pathSlug: 'hmac-generator',
    category: 'encoders',
    icon: Hash,
    title: { ja: 'HMAC生成', en: 'HMAC generator' },
    description: { ja: 'Secret付きメッセージ署名を生成', en: 'Sign messages with a shared secret' },
    mode: 'generate',
    workspace: 'hmac',
  },
  {
    slug: 'basic-auth',
    emoji: '🔐',
    pathSlug: 'basic-auth-generator',
    category: 'encoders',
    icon: LockKeyhole,
    title: { ja: 'Basic認証', en: 'Basic authentication' },
    description: {
      ja: 'Basic認証ヘッダーを生成・解析',
      en: 'Generate and inspect Basic auth headers',
    },
    mode: 'convert',
    workspace: 'basic-auth',
  },
  {
    slug: 'string-escape',
    emoji: '🔤',
    pathSlug: 'string-escape-unescape',
    category: 'encoders',
    icon: Quote,
    title: { ja: '文字列エスケープ', en: 'String escape' },
    description: {
      ja: 'JSON/JS/SQL/正規表現向けにエスケープ',
      en: 'Escape strings for JSON, JS, SQL and regex',
    },
    mode: 'convert',
    workspace: 'string-escape',
  },
  {
    slug: 'json-format',
    emoji: '📘',
    pathSlug: 'json-formatter',
    category: 'formatters',
    icon: Braces,
    title: { ja: 'JSON整形', en: 'JSON formatter' },
    description: { ja: 'JSONを読みやすく整形', en: 'Format and validate JSON' },
    mode: 'convert',
  },
  {
    slug: 'sql-format',
    emoji: '🗃️',
    pathSlug: 'sql-formatter',
    category: 'formatters',
    icon: Code2,
    title: { ja: 'SQL整形', en: 'SQL formatter' },
    description: { ja: 'SQLクエリを整形', en: 'Format SQL queries' },
    mode: 'convert',
  },
  {
    slug: 'xml-format',
    emoji: '🧹',
    pathSlug: 'xml-formatter',
    category: 'formatters',
    icon: Code2,
    title: { ja: 'XML整形', en: 'XML formatter' },
    description: { ja: 'XMLを読みやすく整形', en: 'Format XML documents' },
    mode: 'convert',
  },
  {
    slug: 'yaml-format',
    emoji: '🧵',
    pathSlug: 'yaml-formatter',
    category: 'formatters',
    icon: Layers,
    title: { ja: 'YAML整形', en: 'YAML formatter' },
    description: { ja: 'YAMLを正規化して整形', en: 'Normalise and re-indent YAML' },
    mode: 'convert',
  },
  {
    slug: 'css-format',
    emoji: '💅',
    pathSlug: 'css-formatter',
    category: 'formatters',
    icon: Paintbrush,
    title: { ja: 'CSS整形', en: 'CSS formatter' },
    description: { ja: 'CSSのブロックを読みやすく整形', en: 'Re-indent CSS blocks for reading' },
    mode: 'convert',
  },
  {
    slug: 'html-format',
    emoji: '📰',
    pathSlug: 'html-formatter',
    category: 'formatters',
    icon: FileType,
    title: { ja: 'HTML整形', en: 'HTML formatter' },
    description: { ja: 'HTMLをインデントして整形', en: 'Indent HTML markup' },
    mode: 'convert',
  },
  {
    slug: 'uuid',
    emoji: '🆔',
    pathSlug: 'uuid-generator',
    category: 'generators',
    icon: Fingerprint,
    title: { ja: 'UUID生成', en: 'UUID generator' },
    description: { ja: 'UUID v4をまとめて生成', en: 'Generate UUID v4 values' },
    mode: 'generate',
  },
  {
    slug: 'password',
    emoji: '🔑',
    pathSlug: 'password-generator',
    category: 'generators',
    icon: Sparkles,
    title: { ja: 'パスワード生成', en: 'Password generator' },
    description: { ja: '安全なパスワードを生成', en: 'Generate secure passwords' },
    mode: 'generate',
  },
  {
    slug: 'lorem',
    emoji: '📄',
    pathSlug: 'lorem-ipsum-generator',
    category: 'generators',
    icon: Pilcrow,
    title: { ja: 'ダミーテキスト生成', en: 'Lorem Ipsum generator' },
    description: {
      ja: 'Lorem Ipsumと日本語ダミー文を生成',
      en: 'Generate Lorem Ipsum and Japanese filler text',
    },
    mode: 'generate',
    workspace: 'lorem',
  },
  {
    slug: 'hash',
    emoji: '#️⃣',
    pathSlug: 'hash-generator',
    category: 'generators',
    icon: Hash,
    title: { ja: 'ハッシュ', en: 'Hash' },
    description: { ja: 'SHAハッシュを計算', en: 'Calculate SHA hashes' },
    mode: 'generate',
  },
  {
    slug: 'regex',
    emoji: '🧪',
    pathSlug: 'regular-expression-tester',
    category: 'testers',
    icon: Regex,
    title: { ja: '正規表現テスター', en: 'Regular expression tester' },
    description: {
      ja: '正規表現の一致箇所とグループを確認',
      en: 'Inspect matches and capture groups',
    },
    mode: 'inspect',
    workspace: 'regex',
  },
  {
    slug: 'json-query',
    emoji: '🔍',
    pathSlug: 'jsonpath-schema-validator',
    category: 'testers',
    icon: Route,
    title: { ja: 'JSONPath・Schema検証', en: 'JSONPath & Schema' },
    description: { ja: 'JSONの抽出とSchema検証', en: 'Query and validate JSON data' },
    mode: 'inspect',
    workspace: 'json-query',
  },
  {
    slug: 'selector-tester',
    emoji: '🎯',
    pathSlug: 'css-selector-xpath-tester',
    category: 'testers',
    icon: ListTree,
    title: { ja: 'セレクタ・XPathテスター', en: 'Selector & XPath tester' },
    description: {
      ja: 'HTMLにCSSセレクタとXPathを試す',
      en: 'Run CSS selectors and XPath against HTML',
    },
    mode: 'inspect',
    workspace: 'selector',
  },
  {
    slug: 'glob-tester',
    emoji: '✳️',
    pathSlug: 'glob-pattern-tester',
    category: 'testers',
    icon: Asterisk,
    title: { ja: 'globパターンテスター', en: 'Glob pattern tester' },
    description: {
      ja: 'パスがglobに一致するか確認',
      en: 'Check which paths a glob pattern matches',
    },
    mode: 'inspect',
    workspace: 'glob',
  },
  {
    slug: 'text-analyzer',
    emoji: '🔠',
    pathSlug: 'text-analyzer-case-converter',
    category: 'text',
    icon: CaseSensitive,
    title: { ja: 'テキスト解析・ケース変換', en: 'Text analyzer & case converter' },
    description: { ja: '文字数を解析してケースを変換', en: 'Analyze text and convert its case' },
    mode: 'inspect',
    workspace: 'text-analyzer',
  },
  {
    slug: 'text-diff',
    emoji: '🆚',
    pathSlug: 'text-diff',
    category: 'text',
    icon: GitCompareArrows,
    title: { ja: 'テキストDiff', en: 'Text diff' },
    description: { ja: '2つのテキストの差分を比較', en: 'Compare differences between two texts' },
    mode: 'inspect',
    workspace: 'text-diff',
  },
  {
    slug: 'list-utils',
    emoji: '📋',
    pathSlug: 'list-formatter',
    category: 'text',
    icon: ListOrdered,
    title: { ja: 'リスト整形', en: 'List formatter' },
    description: {
      ja: '並べ替え・重複除去・前後付与をまとめて',
      en: 'Sort, deduplicate and wrap lines in one pass',
    },
    mode: 'convert',
    workspace: 'list-utils',
  },
  {
    slug: 'markdown',
    emoji: '📝',
    pathSlug: 'markdown-preview',
    category: 'text',
    icon: FileText,
    title: { ja: 'Markdownプレビュー', en: 'Markdown preview' },
    description: { ja: 'Markdownを安全にプレビュー', en: 'Safely preview Markdown' },
    mode: 'inspect',
    workspace: 'markdown',
  },
  {
    slug: 'cron',
    emoji: '⏱️',
    pathSlug: 'cron-parser',
    category: 'converters',
    icon: Timer,
    title: { ja: 'Cron式パーサー', en: 'Cron parser' },
    description: { ja: 'Cron式と次回実行日時を確認', en: 'Inspect cron schedules and next runs' },
    mode: 'inspect',
    workspace: 'cron',
  },
  {
    slug: 'qr-code',
    emoji: '📱',
    pathSlug: 'qr-code-generator',
    category: 'generators',
    icon: QrCode,
    title: { ja: 'QRコード生成', en: 'QR code generator' },
    description: { ja: 'テキストからQRコードを生成', en: 'Generate a QR code from text' },
    mode: 'generate',
    workspace: 'qr-code',
  },
  {
    slug: 'base64-image',
    emoji: '🖼️',
    pathSlug: 'base64-image-converter',
    category: 'images',
    icon: FileImage,
    title: { ja: 'Base64画像変換', en: 'Base64 image converter' },
    description: { ja: '画像とData URLを相互変換', en: 'Convert images and Data URLs' },
    mode: 'convert',
    workspace: 'base64-image',
  },
  {
    slug: 'svg-tools',
    emoji: '🖌️',
    pathSlug: 'svg-optimizer',
    category: 'images',
    icon: Blend,
    title: { ja: 'SVG最適化・プレビュー', en: 'SVG optimizer & preview' },
    description: {
      ja: '不要な情報を削りData URIも生成',
      en: 'Strip cruft and emit a CSS-ready data URI',
    },
    mode: 'convert',
    workspace: 'svg',
  },
  {
    slug: 'image-convert',
    emoji: '🗜️',
    pathSlug: 'image-converter',
    category: 'images',
    icon: Crop,
    title: { ja: '画像リサイズ・圧縮', en: 'Image resize & compress' },
    description: {
      ja: 'WebP/AVIF等へ変換しサイズを削減',
      en: 'Convert to WebP/AVIF and shrink the file',
    },
    mode: 'convert',
    workspace: 'image-convert',
  },
  {
    slug: 'exif',
    emoji: '📸',
    pathSlug: 'exif-viewer',
    category: 'images',
    icon: Aperture,
    title: { ja: 'EXIF確認・削除', en: 'EXIF viewer & remover' },
    description: {
      ja: '撮影情報と位置情報を確認して削除',
      en: 'Inspect capture and location data, then strip it',
    },
    mode: 'inspect',
    workspace: 'exif',
  },
  {
    slug: 'subnet',
    emoji: '🕸️',
    pathSlug: 'ipv4-subnet-calculator',
    category: 'network',
    icon: Network,
    title: { ja: 'IPv4サブネット計算', en: 'IPv4 subnet calculator' },
    description: { ja: 'IPv4/CIDRのネットワーク範囲を計算', en: 'Calculate IPv4 network ranges' },
    mode: 'inspect',
    workspace: 'subnet',
  },
  {
    slug: 'url-parser',
    emoji: '🧭',
    pathSlug: 'url-parser',
    category: 'network',
    icon: Link2,
    title: { ja: 'URL解析', en: 'URL parser' },
    description: {
      ja: 'URLの構成要素とクエリを解析',
      en: 'Inspect URL components and query parameters',
    },
    mode: 'inspect',
    workspace: 'url-parser',
  },
  {
    slug: 'site-diagnostics',
    emoji: '🩺',
    pathSlug: 'dns-tls-http-ogp-diagnostics',
    category: 'network',
    icon: Network,
    title: { ja: 'DNS・TLS・HTTP・OGP診断', en: 'DNS, TLS, HTTP & OGP diagnostics' },
    description: {
      ja: 'ドメインとWebページをまとめて診断',
      en: 'Inspect a domain and web page in one request',
    },
    mode: 'inspect',
    workspace: 'site-diagnostics',
  },
  {
    slug: 'network-info',
    emoji: '📡',
    pathSlug: 'connection-info',
    category: 'network',
    icon: Network,
    title: { ja: 'ネットワーク情報', en: 'Network info' },
    description: { ja: 'ブラウザの接続情報を確認', en: 'Inspect browser network details' },
    mode: 'inspect',
  },
]

export const findTool = (slug: string) => tools.find((tool) => tool.slug === slug)
export const findToolByPath = (category: string, pathSlug: string) =>
  tools.find((tool) => tool.category === category && tool.pathSlug === pathSlug)
export const toolsByCategory = (category: ToolCategory) =>
  tools.filter((tool) => tool.category === category)
